version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn install
artifacts:
  files:
    - target/Bibliotheque-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/**/*
  discard-paths: no